Add Homework18
ritabunets/AutoLab pull request #10
Opened 2023-05-02 16:21 UTC by ritabunets

please be patient, I haven't coded since winter)

2023-05-08 14:33 UTC, yauhenists requested changes

2023-05-08 14:33 UTC, yauhenists commented on AdonetProject/AdonetDbHelper.cs
> +        private static string _connectionStringAdonet => ConfigurationHelper.LocalAdonetDbConnectionString;
Naming for properties - starts with upper case

2023-05-08 14:33 UTC, yauhenists commented on AdonetProject/AdonetDbTests.cs
> +            var firstNameInDB = AdonetDbHelper.GetLastAddedValue("FirstName");
You can use constants from the class UsersTableColumns

2023-05-08 14:33 UTC, yauhenists commented on ET_Main/SqlHelper.cs
> +        public static string GetClientExtendedConnectionString(string sqlConnectionString)
It's worth to make it private and move after public methods

2023-05-08 14:33 UTC, yauhenists commented on ET_Main/EntityFrameworkTests.cs
> +            var userInDbFirstName = SqlHelper.GetLastEntryFromUsers(newUser.Id).FirstName;
It's better to get the object from the DB once and check its properties instead of getting the object each time you need to get any property

2023-05-15 12:15 UTC, ritabunets commented on AdonetProject/AdonetDbHelper.cs
> +        private static string _connectionStringAdonet => ConfigurationHelper.LocalAdonetDbConnectionString;
fixed

2023-05-15 12:16 UTC, ritabunets commented on AdonetProject/AdonetDbTests.cs
> +            var firstNameInDB = AdonetDbHelper.GetLastAddedValue("FirstName");
fixed

2023-05-15 12:19 UTC, ritabunets commented on ET_Main/SqlHelper.cs
> +        public static string GetClientExtendedConnectionString(string sqlConnectionString)
done

2023-05-15 12:32 UTC, ritabunets commented on ET_Main/EntityFrameworkTests.cs
> +            var userInDbFirstName = SqlHelper.GetLastEntryFromUsers(newUser.Id).FirstName;
updated

2023-05-23 13:58 UTC, yauhenists approved these changes

2023-05-24 13:09 UTC, merged