Add Homework6
ritabunets/AutoLab pull request #3
Opened 2022-11-14 23:07 UTC by ritabunets

2022-11-16 09:27 UTC, yauhenists requested changes

2022-11-16 09:27 UTC, yauhenists commented on Homework5_Lib/Employee.cs
> +        public const int defaultSalary = 500;
Fields should be private or it can be properties it access to them is required outside the class

2022-11-16 09:27 UTC, yauhenists commented on Homework5_Lib/Entity.cs
> +    public class Entity
Class name 'says' it's better to make it abstract. But leave it as it is

2022-11-16 09:27 UTC, yauhenists commented on Homework5_Lib/Entity.cs
> +        public string entityType;
Do not make fields public, they can be protected they are used in derived classes or private

2022-11-16 09:27 UTC, yauhenists commented on Homework5_Lib/Team.cs
> +        public new void GetEntityData() => Console.WriteLine($"{entityType} | {id} | {_domain} | Manager: {manager}");
I think it's better to inherit and override this method from Entity class

2022-11-16 20:14 UTC, ritabunets commented on Homework5_Lib/Entity.cs
> +    public class Entity
fixed

2022-11-16 20:19 UTC, ritabunets commented on Homework5_Lib/Entity.cs
> +        public string entityType;
fixed

2022-11-16 20:20 UTC, ritabunets commented on Homework5_Lib/Employee.cs
> +        public const int defaultSalary = 500;
fixed

2022-11-16 20:25 UTC, ritabunets commented on Homework5_Lib/Team.cs
> +        public new void GetEntityData() => Console.WriteLine($"{entityType} | {id} | {_domain} | Manager: {manager}");
done

2022-11-17 09:03 UTC, yauhenists requested changes

2022-11-17 09:03 UTC, yauhenists commented on Homework5_Lib/Employee.cs
> +        private const int defaultSalary = 500;
Naming:
private fields - starts with "_"+lower case letter (e.g. private string _lastName)
const - starts with upper case letter (private const int DefaultSalary)
protected - starts with upper case (protected string Name)

2022-11-17 09:18 UTC, ritabunets commented on Homework5_Lib/Employee.cs
> +        private const int defaultSalary = 500;
fixed

2022-11-17 09:35 UTC, yauhenists approved these changes

2022-11-17 09:55 UTC, merged